import { defaultMccOptions } from '../utils/mccAnalysis.js'

const fmt=(v,n=3)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('es-ES',{maximumFractionDigits:n}):'—'
const types={PDD:'PDD',INPLANE_PROFILE:'Inplane',CROSSPLANE_PROFILE:'Crossplane'}

export default function MccBatchResults({scans,settings,results,selected,onSelect,onQuantity}) {
  const pdds=scans.filter(s=>s.type==='PDD'),profiles=scans.filter(s=>s.type!=='PDD')
  const identity=s=>{const o=settings[s.key]||defaultMccOptions(s);return <><th scope="row"><strong>{s.fileName} · #{s.id}</strong><span>{types[s.type]||s.type} · {o.modality==='electron'?`${o.energy||'?'} MeV · electrones`:o.modality==='photon'?`${o.energy||'?'} MV · ${o.filter==='unknown'?'filtro sin confirmar':o.filter}`:'radiación sin confirmar'}</span><span>Campo declarado: {s.metadata.FIELD_INPLANE||'?'} × {s.metadata.FIELD_CROSSPLANE||'?'} mm{s.type!=='PDD'&&` · profundidad: ${s.metadata.SCAN_DEPTH||'?'} mm`}</span></th></>}
  const actions=s=>{const r=results[s.key]||{};return <td><button type="button" aria-label={`Ver análisis ${s.fileName} barrido ${s.id}`} onClick={()=>onSelect(s.key)}>{selected===s.key?'Seleccionado · ajustar':'Ver / ajustar'}</button>{r.error?<p className="mcc-batch-error">{r.error}</p>:r.warnings?.length?<details><summary>{r.warnings.length} avisos</summary><ul>{r.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>:<span className="mcc-note">Sin avisos del cálculo</span>}</td>}
  return <section className="mcc-card" aria-label="Análisis de todos los barridos">
    <h2>Análisis por barrido · {scans.length} resultados</h2>
    <p>Cada PDD y perfil se calcula con sus propios datos y ajustes. Selecciona «Ver / ajustar» para abrir su curva y completar sus condiciones. — significa no evaluable; consulta los avisos de esa fila.</p><p className="mcc-note">Desplaza las tablas horizontalmente para ver todas las columnas en pantallas pequeñas.</p>
    {!!pdds.length&&<><h3>PDD · {pdds.length}</h3><div className="mcc-table-wrap mcc-batch-wrap"><table className="mcc-batch-table"><thead><tr><th>Barrido</th><th>Magnitud</th><th>dₘáx dosis<br/>mm</th><th>PDD₁₀<br/>%</th><th>PDD₂₀<br/>%</th><th>R₅₀ e⁻<br/>g/cm²</th><th>TPR₂₀,₁₀<br/>estimado</th><th>Detalle y avisos</th></tr></thead><tbody>{pdds.map(s=>{const r=results[s.key]||{},o=settings[s.key]||defaultMccOptions(s);return <tr key={s.key} data-scan-key={s.key} aria-selected={selected===s.key}>
      {identity(s)}<td><select aria-label={`Magnitud ${s.fileName} barrido ${s.id}`} value={o.quantity} onChange={e=>onQuantity(s.key,e.target.value)}><option value="unknown">Confirmar…</option><option value="dose">Dosis / detector validado</option><option value="ion">Ionización</option></select></td><td>{fmt(r.metrics?.dmax)}</td><td>{fmt(r.metrics?.pdd10)}</td><td>{fmt(r.metrics?.pdd20)}</td><td>{fmt(r.electron?.r50)}</td><td>{fmt(r.tpr,5)}{r.tprInfo?.filter==='FFF'&&<span className="mcc-batch-tag">FFF · aproximado</span>}</td>{actions(s)}</tr>})}</tbody></table></div></>}
    {!!profiles.length&&<><h3>Perfiles · {profiles.length}</h3><div className="mcc-table-wrap mcc-batch-wrap"><table className="mcc-batch-table"><thead><tr><th>Barrido</th><th>FWHM<br/>mm</th><th>Centro − CAX<br/>mm</th><th>Penumbra I / D<br/>mm · 80–20</th><th>Simetría<br/>%</th><th>Planitud WFF<br/>%</th><th>Cociente FFF<br/>CAX / ±80%</th><th>Inflexiones<br/>distancia mm</th><th>Detalle y avisos</th></tr></thead><tbody>{profiles.map(s=>{const r=results[s.key]||{},m=r.metrics;return <tr key={s.key} data-scan-key={s.key} aria-selected={selected===s.key}>{identity(s)}<td>{fmt(m?.width)}</td><td>{fmt(m?.centerDeviation)}</td><td>{fmt(m?.penumbraLeft)} / {fmt(m?.penumbraRight)}</td><td>{fmt(m?.symmetry)}</td><td>{fmt(m?.flatness)}</td><td>{fmt(m?.unflatness)}</td><td>{fmt(m?.inflectionWidth)}</td>{actions(s)}</tr>})}</tbody></table></div></>}
  </section>
}
